os: linux
dist: xenial
language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - nightly

cache:
    directories:
        - $HOME/.composer/cache

jobs:
    fast_finish: true
    allow_failures:
        - php: nightly
    include:
        - php: 5.3
          dist: precise
        - php: 5.4
          dist: precise
        - php: 5.5
          dist: trusty
        - php: 5.6
          dist: trusty

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install:
  - composer install --prefer-dist --no-progress --no-suggest -o

script:
  - "cd tests && php -dshort_open_tag=Off -dmagic_quotes_gpc=Off run.php"
