version: '3.5'

volumes:
  db_socket:

services:
  composer:
    image: composer
    working_dir: /app
    volumes:
      - .:/app
    entrypoint:
      - sh
      - -c
      - |
        exec tail -f /dev/null

  php82:
    <<: *services_php8x
    build:
      context: .docker/php74_82
      args:
        PHP_VERSION: '8.2'

  db:
    image: mysql:5.5.62
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db_socket:/tmp
    entrypoint:
      - bash
      - -c
      - |
        {
            echo "CREATE DATABASE IF NOT EXISTS test;"
        } | tee /docker-entrypoint-initdb.d/init.sql

        exec /usr/local/bin/docker-entrypoint.sh mysqld
